version: '3'

services:
  app:
    build: .
    image: my-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"